박스히어로 일렉트론 1.0.0
bgpworks/boxhero-electron pull request #13
Opened 2020-10-20 10:10 UTC by BitYoungjae

2020-10-21 00:51 UTC, BitYoungjae commented
# 현재 문제
- 프린터 출력시 멈추는 현상
- 메뉴 설정 및 각종 ipcMain 핸들러들이 특정 윈도에 종속적임.

2020-11-03 07:08 UTC, jngbng requested changes
변경 후 v.0.3.1 업그레이드 테스트.

2020-11-03 07:08 UTC, jngbng commented on src/electron/utils/persistWindowState.ts
> +const logFileName = 'window_state.json';
lastWindowStateFileName 정도로?

2020-11-03 07:08 UTC, jngbng commented on src/electron/utils/persistWindowState.ts
> +let logPath: string;
lastWindowStateFilePath

2020-11-03 07:08 UTC, jngbng commented on locales/en/electron/menu.json
> +  "view_zomm_out": "Zoom Out",
view_zoom_out 오타

2020-11-03 07:08 UTC, jngbng commented on src/electron/main.ts
> +   * 구글 인증이 안되는 문제에 대한 미봉책. */
해결책 링크도 남겨둔다.
https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow

2020-11-03 10:47 UTC, jngbng requested changes
에러에서 로그 남기고, 오래된 로그가 알아서 지워져서 전체 파일 크기가 일정 크기 이하로 유지되는지 확인 필요하네요.
그리고 LoadingIndicator 부분은 구현이 묘한데, 좀 살펴봐야겠네요.

2020-11-03 10:47 UTC, jngbng commented on src/electron/utils/persistWindowState.ts
> +    log.error('window state 파일 읽기에 실패.');
exception 을 같이 찍어주는게 좋죠.

2020-11-03 10:47 UTC, jngbng commented on src/electron/utils/persistWindowState.ts
> +    // silent fail
로그를 찍어주는게 좋죠.

2020-11-03 10:47 UTC, jngbng commented on src/react/components/LoadingIndicator/index.tsx
> +  const isOpened = useRef(false);
이건 dom 접근하는 hook인데 사용법이 상당히 이상한데요?! useState하면 안되는 이유가 있나요?

2020-11-03 13:53 UTC, BitYoungjae commented on src/react/components/LoadingIndicator/index.tsx
> +  const isOpened = useRef(false);
https://react.vlpt.us/basic/12-variable-with-useRef.html

위 내용을 어렴풋이 기억하고 사용했던 것인데
굳이 이 경우에는 불필요한 것 같네요ㅠ 다시 useState로 바꾸겠습니다 ㅋㅋ;

2020-11-03 23:32 UTC, BitYoungjae commented
> 에러에서 로그 남기고, 오래된 로그가 알아서 지워져서 전체 파일 크기가 일정 크기 이하로 유지되는지 확인 필요하네요.
> 그리고 LoadingIndicator 부분은 구현이 묘한데, 좀 살펴봐야겠네요.

electron-log 코드 확인시
로그 사이즈가 1mb(기본값)가 넘을시
기존 로그 파일을 이름에 .old를 붙여서 이동시킴
기존 old 파일은 덮어씌워짐.

2020-11-03 23:49 UTC, BitYoungjae commented
Unhandled error에 대한 설정 추가 필요

https://github.com/megahertz/electron-log/blob/HEAD/docs/catch.md

2020-11-04 00:08 UTC, BitYoungjae commented
editor config 추가할 것

2020-11-10 07:58 UTC, jngbng commented
/deploy

2020-11-10 08:00 UTC, jngbng commented
/deploy

2020-11-10 08:08 UTC, jngbng commented
/deploy

2020-11-10 08:14 UTC, jngbng approved these changes

2020-11-10 08:15 UTC, jngbng commented
/deploy

2020-11-10 08:20 UTC, BitYoungjae commented
/deploy

2020-11-10 08:21 UTC, merged